innogames/slack-bot

- bot/util/slack.go
- bot/util/slack_test.go
- command/queue/list.go
- command/queue/queue_test.go
- mocks/testing.go
> list queue: colorize message (split attachment per queued command)

- bot/tester/tester.go
- cmd/cli/main.go
> #21 cmd/cli currently not working

- command/cron/command.go
- go.mod
Changes are included on this list:
https://github.com/robfig/cron/blob/e7da914f1b8ad11451fae2a1e3dad602f43cc837/README.md
> Upgraded cron lib to support CRON_TZ=*TIMEZONE*

- bot/bot.go
- bot/interaction/server.go
- bot/stats/stats.go
- bot/stats/stats_test.go
- bot/storage/file.go
- bot/storage/storage.go
- bot/storage/storage_test.go
- command/admin/stats.go
- command/admin/stats_test.go
- command/queue/queue.go
- readme.md
Example result:
```
Runtime stats:
- Goroutines: 8 goroutines
Processed commands:
- Total Commands: 31
- Unknown Commands: 10
- Unauthorized Commands: 0
- Queued commands: 1
```
> added stats command to display runtime bot stats

- bot/command.go
- command/jenkins/build_watcher.go
- command/jenkins/build_watcher_test.go
- command/jenkins/commands.go
- command/jenkins/commands_test.go
- command/jenkins/inform_idle.go
- command/jenkins/inform_idle_test.go
- command/jenkins/job_status.go
- command/jenkins/job_status_test.go
- command/jenkins/job_watcher.go
- command/jenkins/job_watcher_test.go
- command/jenkins/nodes.go
- command/jenkins/nodes_test.go
- command/jenkins/retry_build.go
- command/jenkins/retry_build_test.go
- command/jenkins/trigger.go
- command/jenkins/trigger_test.go
> feature: New command to wait until Jenkins is idle #53

- bot/server/event_test.go
- bot/storage/file.go
- client/slack.go
- command/cron/command.go
- command/retry.go
- command/retry_test.go
- go.mod
- mocks/SlackClient.go
> feature: add a way to post any link to an own message to interpret it as a message

- bot/util/template.go
- command/defined_commands.go
- command/defined_commands_test.go
- command/variables/template.go
- fixed pointer receiver for "customVariable"
- added new command "list template function" to check all available ones
> fixed: 'function "customVariable" not defined' in user defined commands

- command/pullrequest/pull_request.go
- wait before next retry
- "panic": "panic: errors: *target must be interface or implement error"
> pullrequest: improve error handling

- bot/bot.go
- client/slack.go
- client/slack_test.go
- command/pullrequest/pull_request.go
- command/queue/list.go
added link to the messages, see here:
> enhancement: add message link to "list queue" to jump directly to queued messages

- .golangci.yml
- bot/config/config.go
- bot/config/config_test.go
- bot/config/default.go
- bot/config/loader.go
- bot/config/pull_request.go
- command/pullrequest/bitbucket_test.go
- command/pullrequest/github_test.go
- command/pullrequest/pull_request.go
- command/pullrequest/pull_request_test.go
- config.example.yaml
- go.mod
**Example:**
```
pullrequest:
reactions:
merged: merge_arrow
error: fire
```
> feat: make pullrequest reactions customizable #48

- bot/interaction.go
- bot/msg/ref.go
- client/slack.go
- command/delay.go
- command/pullrequest/pull_request.go
- command/queue/list_command.go
- command/queue/queue_test.go
- mocks/testing.go
E.g. to update the  list of open pull requests
> enhancement: add "Refresh" button to "list queue". 

- bot/interaction.go
- bot/stats/stats.go
- command/admin/stats.go
> enhancement: added stat counter for pressed buttons/interactions

- .github/workflows/test.yaml
- bot/util/delay_test.go
- bot/util/duration.go
- bot/util/duration_test.go
- command/delay_test.go
-> show "5d1h9m46s ago" instead of "121h9m46s"
> enhancement: show days in util.FormatDuration()

- bot/bot.go
- go.mod
- go.sum
see https://github.com/slack-go/slack/releases/tag/v0.9.0
> dependency: upgraded github.com/slack-go/slack  to 0.9.0

- bot/util/format.go
- bot/util/format_test.go
- command/admin/stats.go
- go.mod
- show more useful metrics
- better integer formatting
> improve "bot stats"

- .air.toml
- Makefile
- readme.md
see https://github.com/cosmtrek/air
> enhancement: add "make air" to use auto reload

- bot/bot.go
- bot/msg/message_test.go
- bot/msg/ref.go
- command/admin/bot_log_test.go
- command/admin/commands.go
- command/admin/ping.go
- command/admin/ping_test.go
- command/queue/queue_test.go
Prints the needed time from client -> slack server -> slack bot server -> executed pingCommand
> Ping command

- Makefile
- bot/bot.go
- bot/bot_test.go
- bot/interaction.go
- bot/listener.go
- cmd/bot/main.go
- cmd/cli/main.go
- remove more stuff from cmd/bot/man.go
- make it easier to add commands to the bot.Commands set
> make it easier to fork the project with custom commands (part 1)

- client/slack.go
- command/defined_commands.go
- command/help.go
- command/jenkins/build_watcher_test.go
- command/jenkins/inform_idle.go
- command/jenkins/inform_idle_test.go
- command/jenkins/job_status_test.go
- command/retry.go
- command/weather/weather.go
- command/weather/weather_test.go
- better structure (linebreak between categories)
- group command better into the categories
> enhancement: improve help

- .github/workflows/test.yaml
- bot/storage/memory.go
- bot/storage/redis.go
- bot/storage/storage.go
- bot/tester/tester.go
- bot/util/template.go
- bot/util/template_test.go
- client/vcs/bitbucket.go
gofmt -w -r 'interface{} -> any' src
> change all interface{} to any

- command/pullrequest/pull_request.go
- it’s not garanteed that the pr author in gitlab / bitbucken / github is also the observer via slack so i changed the notification to the slack observer instead
> use message author for response

- .gitignore
- command/clouds/aws/commands.go
- command/clouds/aws/ecs.go
Hello!
As an ECS user I'd like to have covered common operations: restart, list services, scale, rollback, etc. For now I'm including the first two.
> add ecs command for aws

- .golangci.yml
> remove abandoned linters

- bot/command.go
- bot/config/config.go
- bot/config/pool.go
- bot/fallback.go
- bot/interaction_test.go
- bot/listener.go
- client/slack.go
- command/add_button.go
- command/add_button_test.go
- command/commands.go
- command/delay.go
- command/delay_test.go
- command/games/quiz.go
- command/games/quiz_test.go
- command/pool/commands.go
- command/pool/pool.go
- command/pool/pool_commands.go
- command/pullrequest/pull_request.go
- command/queue/list_command.go
- config.example.yaml
- mocks/SlackClient.go
defines a pool of resources which can be locked by the bot
can be used to share resources in the team like servers, devices, books, ...
> add pool of resources to maintain locks for

- bot/bot.go
- show admin usernames
- show user name in the log
> improve "you are not whitelisted" message

- bot/bot_handle.go
- bot/bot_handle_test.go
- bot/bot_init.go
- bot/bot_init_test.go
- bot/command.go
- bot/config/dump.go
- bot/config/dump_test.go
- bot/stats/stats.go
- bot/storage/storage_test.go
- cmd/bot/main.go
- command/admin/stats.go
- command/admin/stats_test.go
- command/games/config.go
- command/pool/commands_test.go
track command names in logs and bot stats
> Command names

- bot/bot_handle.go
- bot/bot_handle_test.go
- bot/config/config.go
- bot/interaction.go
- client/http.go
- command/clouds/aws/commands.go
- command/jenkins/trigger.go
- command/jenkins/trigger_test.go
- command/openai/command.go
set `no_authentication: true` to bypass whitelist and allow all user actions within the current workspace
> Add an option to disable authentication via whitelist

- bot/util/contains.go
- bot/util/contains_test.go
- command/pullrequest/pull_request.go
- command/pullrequest/pull_request_test.go
> remove all needed approve reaction on revoked pullrequest

- command/pool/pool_commands.go
CWE-118: Implicit memory aliasing in for loop
> gosec: avoid security warning

- Dockerfile
- bot/command.go
- bot/config/config.go
- bot/config/config_test.go
- bot/config/default.go
- bot/config/vcs.go
- bot/listener.go
- client/slack.go
- client/vcs/vcs.go
- client/vcs/vcs_test.go
- command/commands.go
- command/pool/pool_commands.go
- command/vcs/command.go
- command/vcs/vcs_test.go
-> move into dedicated package/command
> WIP: cleanup VCS/BranchLookup

- command/openai/command.go
- command/openai/openai_test.go
- command/openai/tokens.go
- command/openai/tokens_test.go
- go.mod
- go.sum
-  truncate input message if tokens exceeding
- support adding context from another thread
> Openai: truncate input message if tokens exceeding

- command/commands.go
- command/export/export.go
> export channel as CSV

- bot/util/delay_test.go
- command/openai/api.go
- command/openai/config.go
- command/openai/dalle.go
- command/openai/dalle_test.go
> Dall-E: 2nd button + add "quality" option

- command/jenkins/inform_idle.go
- command/jenkins/inform_idle_test.go
allow hosts like "foo-jenkins.local"
> jenkins: allow more characters in "wait until jenkins <node> is idle" command

- client/slack.go
- command/defined_commands_test.go
- as they can be the result of template tags
> defined commands: ignore empty lines

- bot/config/default.go
- bot/config/pull_request.go
- command/pullrequest/bitbucket.go
- command/pullrequest/github.go
- command/pullrequest/github_test.go
- command/pullrequest/gitlab.go
- command/pullrequest/pull_request.go
- command/pullrequest/pull_request_test.go
- Add bot functionality, which notifies a PR author when new review comments are added
- Review comments are compared based on the created timestamp
- As an MVP currently only implemented for Bitbucket
- Notification can be turned off via config
> Slack notifications for new review comments
